"""empty message

Revision ID: 9404c48b2dbf
Revises: ef8d0d1166f7
Create Date: 2023-05-19 20:59:59.883277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9404c48b2dbf'
down_revision = 'ef8d0d1166f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=25), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.String(length=25), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###
